// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  WATERMELON007
// DateTime: 7/5/2020 2:54:24 PM
// UserName: moska
// Input file <kompilator.y - 7/5/2020 2:54:04 PM>

// options: conflicts lines gplex conflicts

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace GardensPoint
{
public enum Tokens {error=2,EOF=3,Program=4,If=5,Else=6,
    While=7,Read=8,Write=9,Return=10,Int=11,Double=12,
    Bool=13,Assign=14,OpenPar=15,ClosePar=16,OpenBr=17,CloseBr=18,
    Semicolon=19,Endl=20,Eof=21,Error=22,Plus=23,Minus=24,
    Multiplies=25,Divides=26,LogicOr=27,LogicAnd=28,BitOr=29,BitAnd=30,
    Equal=31,NotEqual=32,More=33,MoreEqual=34,Less=35,LessEqual=36,
    LogicNeg=37,BitNeg=38,Ident=39,IntNumber=40,DoubleNumber=41,Str=42,
    True=43,False=44};

public struct ValueType
#line 5 "kompilator.y"
{
public string  val;
public Compiler.SyntaxTree node;
}
#line default
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[66];
  private static State[] states = new State[122];
  private static string[] nonTerms = new string[] {
      "expr", "exprRelation", "exprAdd", "exprMul", "exprBit", "exprUn", "value", 
      "write_stmt", "read_stmt", "return_stmt", "if_stmt", "block", "expr_list", 
      "statements", "while_stmt", "exprLogic", "expr_instruction", "program", 
      "start", "$accept", "dec_list", "declaration", };

  static Parser() {
    states[0] = new State(new int[]{4,5,2,119,21,121},new int[]{-19,1,-18,3});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{21,4});
    states[4] = new State(-2);
    states[5] = new State(new int[]{17,6});
    states[6] = new State(new int[]{18,7,11,110,12,113,13,116,5,15,7,23,8,30,9,34,39,37,24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,10,100,17,102},new int[]{-21,8,-13,106,-22,108,-14,12,-11,14,-15,22,-9,28,-8,32,-17,95,-1,96,-16,40,-2,72,-3,92,-4,83,-5,82,-6,81,-7,61,-10,98,-12,101});
    states[7] = new State(-5);
    states[8] = new State(new int[]{18,9,5,15,7,23,8,30,9,34,39,37,24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,10,100,17,102},new int[]{-13,10,-14,12,-11,14,-15,22,-9,28,-8,32,-17,95,-1,96,-16,40,-2,72,-3,92,-4,83,-5,82,-6,81,-7,61,-10,98,-12,101});
    states[9] = new State(-6);
    states[10] = new State(new int[]{18,11});
    states[11] = new State(-8);
    states[12] = new State(new int[]{5,15,7,23,8,30,9,34,39,37,24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,10,100,17,102,18,-16},new int[]{-13,13,-14,12,-11,14,-15,22,-9,28,-8,32,-17,95,-1,96,-16,40,-2,72,-3,92,-4,83,-5,82,-6,81,-7,61,-10,98,-12,101});
    states[13] = new State(-17);
    states[14] = new State(-18);
    states[15] = new State(new int[]{15,16});
    states[16] = new State(new int[]{39,37,24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65},new int[]{-1,17,-16,40,-2,72,-3,92,-4,83,-5,82,-6,81,-7,61});
    states[17] = new State(new int[]{16,18});
    states[18] = new State(new int[]{5,15,7,23,8,30,9,34,39,37,24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,10,100,17,102},new int[]{-14,19,-11,14,-15,22,-9,28,-8,32,-17,95,-1,96,-16,40,-2,72,-3,92,-4,83,-5,82,-6,81,-7,61,-10,98,-12,101});
    states[19] = new State(new int[]{6,20,5,-26,7,-26,8,-26,9,-26,39,-26,24,-26,38,-26,37,-26,15,-26,40,-26,41,-26,43,-26,44,-26,10,-26,17,-26,18,-26});
    states[20] = new State(new int[]{5,15,7,23,8,30,9,34,39,37,24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,10,100,17,102},new int[]{-14,21,-11,14,-15,22,-9,28,-8,32,-17,95,-1,96,-16,40,-2,72,-3,92,-4,83,-5,82,-6,81,-7,61,-10,98,-12,101});
    states[21] = new State(-25);
    states[22] = new State(-19);
    states[23] = new State(new int[]{15,24});
    states[24] = new State(new int[]{39,37,24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65},new int[]{-1,25,-16,40,-2,72,-3,92,-4,83,-5,82,-6,81,-7,61});
    states[25] = new State(new int[]{16,26});
    states[26] = new State(new int[]{5,15,7,23,8,30,9,34,39,37,24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,10,100,17,102},new int[]{-14,27,-11,14,-15,22,-9,28,-8,32,-17,95,-1,96,-16,40,-2,72,-3,92,-4,83,-5,82,-6,81,-7,61,-10,98,-12,101});
    states[27] = new State(-27);
    states[28] = new State(new int[]{19,29});
    states[29] = new State(-20);
    states[30] = new State(new int[]{39,31});
    states[31] = new State(-28);
    states[32] = new State(new int[]{19,33});
    states[33] = new State(-21);
    states[34] = new State(new int[]{42,36,39,37,24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65},new int[]{-1,35,-16,40,-2,72,-3,92,-4,83,-5,82,-6,81,-7,61});
    states[35] = new State(-29);
    states[36] = new State(-30);
    states[37] = new State(new int[]{14,38,29,-65,30,-65,25,-65,26,-65,23,-65,24,-65,31,-65,32,-65,33,-65,34,-65,35,-65,36,-65,27,-65,28,-65,19,-65,16,-65});
    states[38] = new State(new int[]{39,37,24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65},new int[]{-1,39,-16,40,-2,72,-3,92,-4,83,-5,82,-6,81,-7,61});
    states[39] = new State(-33);
    states[40] = new State(new int[]{27,41,28,93,19,-34,16,-34});
    states[41] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-2,42,-3,92,-4,83,-5,82,-6,81,-7,61});
    states[42] = new State(new int[]{31,43,32,73,33,84,34,86,35,88,36,90,27,-35,28,-35,19,-35,16,-35});
    states[43] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-3,44,-4,83,-5,82,-6,81,-7,61});
    states[44] = new State(new int[]{23,45,24,75,31,-38,32,-38,33,-38,34,-38,35,-38,36,-38,27,-38,28,-38,19,-38,16,-38});
    states[45] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-4,46,-5,82,-6,81,-7,61});
    states[46] = new State(new int[]{25,47,26,77,23,-45,24,-45,31,-45,32,-45,33,-45,34,-45,35,-45,36,-45,27,-45,28,-45,19,-45,16,-45});
    states[47] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-5,48,-6,81,-7,61});
    states[48] = new State(new int[]{29,49,30,79,25,-48,26,-48,23,-48,24,-48,31,-48,32,-48,33,-48,34,-48,35,-48,36,-48,27,-48,28,-48,19,-48,16,-48});
    states[49] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-6,50,-7,61});
    states[50] = new State(-51);
    states[51] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-6,52,-7,61});
    states[52] = new State(-54);
    states[53] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-6,54,-7,61});
    states[54] = new State(-55);
    states[55] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-6,56,-7,61});
    states[56] = new State(-56);
    states[57] = new State(new int[]{11,58,12,67,39,37,24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65},new int[]{-1,70,-16,40,-2,72,-3,92,-4,83,-5,82,-6,81,-7,61});
    states[58] = new State(new int[]{16,59});
    states[59] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-6,60,-7,61});
    states[60] = new State(-57);
    states[61] = new State(-60);
    states[62] = new State(-61);
    states[63] = new State(-62);
    states[64] = new State(-63);
    states[65] = new State(-64);
    states[66] = new State(-65);
    states[67] = new State(new int[]{16,68});
    states[68] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-6,69,-7,61});
    states[69] = new State(-58);
    states[70] = new State(new int[]{16,71});
    states[71] = new State(-59);
    states[72] = new State(new int[]{31,43,32,73,33,84,34,86,35,88,36,90,27,-37,28,-37,19,-37,16,-37});
    states[73] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-3,74,-4,83,-5,82,-6,81,-7,61});
    states[74] = new State(new int[]{23,45,24,75,31,-39,32,-39,33,-39,34,-39,35,-39,36,-39,27,-39,28,-39,19,-39,16,-39});
    states[75] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-4,76,-5,82,-6,81,-7,61});
    states[76] = new State(new int[]{25,47,26,77,23,-46,24,-46,31,-46,32,-46,33,-46,34,-46,35,-46,36,-46,27,-46,28,-46,19,-46,16,-46});
    states[77] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-5,78,-6,81,-7,61});
    states[78] = new State(new int[]{29,49,30,79,25,-49,26,-49,23,-49,24,-49,31,-49,32,-49,33,-49,34,-49,35,-49,36,-49,27,-49,28,-49,19,-49,16,-49});
    states[79] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-6,80,-7,61});
    states[80] = new State(-52);
    states[81] = new State(-53);
    states[82] = new State(new int[]{29,49,30,79,25,-50,26,-50,23,-50,24,-50,31,-50,32,-50,33,-50,34,-50,35,-50,36,-50,27,-50,28,-50,19,-50,16,-50});
    states[83] = new State(new int[]{25,47,26,77,23,-47,24,-47,31,-47,32,-47,33,-47,34,-47,35,-47,36,-47,27,-47,28,-47,19,-47,16,-47});
    states[84] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-3,85,-4,83,-5,82,-6,81,-7,61});
    states[85] = new State(new int[]{23,45,24,75,31,-40,32,-40,33,-40,34,-40,35,-40,36,-40,27,-40,28,-40,19,-40,16,-40});
    states[86] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-3,87,-4,83,-5,82,-6,81,-7,61});
    states[87] = new State(new int[]{23,45,24,75,31,-41,32,-41,33,-41,34,-41,35,-41,36,-41,27,-41,28,-41,19,-41,16,-41});
    states[88] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-3,89,-4,83,-5,82,-6,81,-7,61});
    states[89] = new State(new int[]{23,45,24,75,31,-42,32,-42,33,-42,34,-42,35,-42,36,-42,27,-42,28,-42,19,-42,16,-42});
    states[90] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-3,91,-4,83,-5,82,-6,81,-7,61});
    states[91] = new State(new int[]{23,45,24,75,31,-43,32,-43,33,-43,34,-43,35,-43,36,-43,27,-43,28,-43,19,-43,16,-43});
    states[92] = new State(new int[]{23,45,24,75,31,-44,32,-44,33,-44,34,-44,35,-44,36,-44,27,-44,28,-44,19,-44,16,-44});
    states[93] = new State(new int[]{24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,39,66},new int[]{-2,94,-3,92,-4,83,-5,82,-6,81,-7,61});
    states[94] = new State(new int[]{31,43,32,73,33,84,34,86,35,88,36,90,27,-36,28,-36,19,-36,16,-36});
    states[95] = new State(-22);
    states[96] = new State(new int[]{19,97});
    states[97] = new State(-32);
    states[98] = new State(new int[]{19,99});
    states[99] = new State(-23);
    states[100] = new State(-31);
    states[101] = new State(-24);
    states[102] = new State(new int[]{18,105,5,15,7,23,8,30,9,34,39,37,24,51,38,53,37,55,15,57,40,62,41,63,43,64,44,65,10,100,17,102},new int[]{-13,103,-14,12,-11,14,-15,22,-9,28,-8,32,-17,95,-1,96,-16,40,-2,72,-3,92,-4,83,-5,82,-6,81,-7,61,-10,98,-12,101});
    states[103] = new State(new int[]{18,104});
    states[104] = new State(-14);
    states[105] = new State(-15);
    states[106] = new State(new int[]{18,107});
    states[107] = new State(-7);
    states[108] = new State(new int[]{11,110,12,113,13,116,18,-9,5,-9,7,-9,8,-9,9,-9,39,-9,24,-9,38,-9,37,-9,15,-9,40,-9,41,-9,43,-9,44,-9,10,-9,17,-9},new int[]{-21,109,-22,108});
    states[109] = new State(-10);
    states[110] = new State(new int[]{39,111});
    states[111] = new State(new int[]{19,112});
    states[112] = new State(-11);
    states[113] = new State(new int[]{39,114});
    states[114] = new State(new int[]{19,115});
    states[115] = new State(-12);
    states[116] = new State(new int[]{39,117});
    states[117] = new State(new int[]{19,118});
    states[118] = new State(-13);
    states[119] = new State(new int[]{21,120});
    states[120] = new State(-3);
    states[121] = new State(-4);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-20, new int[]{-19,3});
    rules[2] = new Rule(-19, new int[]{-18,21});
    rules[3] = new Rule(-19, new int[]{2,21});
    rules[4] = new Rule(-19, new int[]{21});
    rules[5] = new Rule(-18, new int[]{4,17,18});
    rules[6] = new Rule(-18, new int[]{4,17,-21,18});
    rules[7] = new Rule(-18, new int[]{4,17,-13,18});
    rules[8] = new Rule(-18, new int[]{4,17,-21,-13,18});
    rules[9] = new Rule(-21, new int[]{-22});
    rules[10] = new Rule(-21, new int[]{-22,-21});
    rules[11] = new Rule(-22, new int[]{11,39,19});
    rules[12] = new Rule(-22, new int[]{12,39,19});
    rules[13] = new Rule(-22, new int[]{13,39,19});
    rules[14] = new Rule(-12, new int[]{17,-13,18});
    rules[15] = new Rule(-12, new int[]{17,18});
    rules[16] = new Rule(-13, new int[]{-14});
    rules[17] = new Rule(-13, new int[]{-14,-13});
    rules[18] = new Rule(-14, new int[]{-11});
    rules[19] = new Rule(-14, new int[]{-15});
    rules[20] = new Rule(-14, new int[]{-9,19});
    rules[21] = new Rule(-14, new int[]{-8,19});
    rules[22] = new Rule(-14, new int[]{-17});
    rules[23] = new Rule(-14, new int[]{-10,19});
    rules[24] = new Rule(-14, new int[]{-12});
    rules[25] = new Rule(-11, new int[]{5,15,-1,16,-14,6,-14});
    rules[26] = new Rule(-11, new int[]{5,15,-1,16,-14});
    rules[27] = new Rule(-15, new int[]{7,15,-1,16,-14});
    rules[28] = new Rule(-9, new int[]{8,39});
    rules[29] = new Rule(-8, new int[]{9,-1});
    rules[30] = new Rule(-8, new int[]{9,42});
    rules[31] = new Rule(-10, new int[]{10});
    rules[32] = new Rule(-17, new int[]{-1,19});
    rules[33] = new Rule(-1, new int[]{39,14,-1});
    rules[34] = new Rule(-1, new int[]{-16});
    rules[35] = new Rule(-16, new int[]{-16,27,-2});
    rules[36] = new Rule(-16, new int[]{-16,28,-2});
    rules[37] = new Rule(-16, new int[]{-2});
    rules[38] = new Rule(-2, new int[]{-2,31,-3});
    rules[39] = new Rule(-2, new int[]{-2,32,-3});
    rules[40] = new Rule(-2, new int[]{-2,33,-3});
    rules[41] = new Rule(-2, new int[]{-2,34,-3});
    rules[42] = new Rule(-2, new int[]{-2,35,-3});
    rules[43] = new Rule(-2, new int[]{-2,36,-3});
    rules[44] = new Rule(-2, new int[]{-3});
    rules[45] = new Rule(-3, new int[]{-3,23,-4});
    rules[46] = new Rule(-3, new int[]{-3,24,-4});
    rules[47] = new Rule(-3, new int[]{-4});
    rules[48] = new Rule(-4, new int[]{-4,25,-5});
    rules[49] = new Rule(-4, new int[]{-4,26,-5});
    rules[50] = new Rule(-4, new int[]{-5});
    rules[51] = new Rule(-5, new int[]{-5,29,-6});
    rules[52] = new Rule(-5, new int[]{-5,30,-6});
    rules[53] = new Rule(-5, new int[]{-6});
    rules[54] = new Rule(-6, new int[]{24,-6});
    rules[55] = new Rule(-6, new int[]{38,-6});
    rules[56] = new Rule(-6, new int[]{37,-6});
    rules[57] = new Rule(-6, new int[]{15,11,16,-6});
    rules[58] = new Rule(-6, new int[]{15,12,16,-6});
    rules[59] = new Rule(-6, new int[]{15,-1,16});
    rules[60] = new Rule(-6, new int[]{-7});
    rules[61] = new Rule(-7, new int[]{40});
    rules[62] = new Rule(-7, new int[]{41});
    rules[63] = new Rule(-7, new int[]{43});
    rules[64] = new Rule(-7, new int[]{44});
    rules[65] = new Rule(-7, new int[]{39});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // start -> program, Eof
#line 18 "kompilator.y"
    {
				YYAccept();
				}
#line default
        break;
      case 3: // start -> error, Eof
#line 22 "kompilator.y"
    { 
				++Compiler.errors;
				Console.WriteLine("error"); 
				yyerrok();
				YYAbort();
				}
#line default
        break;
      case 4: // start -> Eof
#line 29 "kompilator.y"
    { 
				++Compiler.errors;
				Console.WriteLine("Unexpected EOF"); 
				yyerrok();
				YYAbort();
				}
#line default
        break;
      case 5: // program -> Program, OpenBr, CloseBr
#line 38 "kompilator.y"
    {
				Compiler.root = new Compiler.ProgramTree(null, Compiler.lineno);
				}
#line default
        break;
      case 6: // program -> Program, OpenBr, dec_list, CloseBr
#line 42 "kompilator.y"
    {
				Compiler.root = new Compiler.ProgramTree(null, Compiler.lineno);
				}
#line default
        break;
      case 7: // program -> Program, OpenBr, expr_list, CloseBr
#line 46 "kompilator.y"
    {
				Compiler.root = new Compiler.ProgramTree(ValueStack[ValueStack.Depth-2].node, Compiler.lineno);
				}
#line default
        break;
      case 8: // program -> Program, OpenBr, dec_list, expr_list, CloseBr
#line 50 "kompilator.y"
    {
				Compiler.root = new Compiler.ProgramTree(ValueStack[ValueStack.Depth-2].node, Compiler.lineno);
				}
#line default
        break;
      case 11: // declaration -> Int, Ident, Semicolon
#line 61 "kompilator.y"
    {
				Compiler.DeclareNewVariable(ValueStack[ValueStack.Depth-2].val, Tokens.Int, Compiler.lineno);
				}
#line default
        break;
      case 12: // declaration -> Double, Ident, Semicolon
#line 65 "kompilator.y"
    {
				Compiler.DeclareNewVariable(ValueStack[ValueStack.Depth-2].val, Tokens.Double, Compiler.lineno);
				}
#line default
        break;
      case 13: // declaration -> Bool, Ident, Semicolon
#line 69 "kompilator.y"
    {
				Compiler.DeclareNewVariable(ValueStack[ValueStack.Depth-2].val, Tokens.Bool, Compiler.lineno);
				}
#line default
        break;
      case 14: // block -> OpenBr, expr_list, CloseBr
#line 75 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-2].node;
				}
#line default
        break;
      case 15: // block -> OpenBr, CloseBr
#line 79 "kompilator.y"
    {
				Compiler.EmptyBrackets n = new Compiler.EmptyBrackets(Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 16: // expr_list -> statements
#line 86 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
				}
#line default
        break;
      case 17: // expr_list -> statements, expr_list
#line 90 "kompilator.y"
    {
				Compiler.ExprList n = new Compiler.ExprList(ValueStack[ValueStack.Depth-2].node, ValueStack[ValueStack.Depth-1].node, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 18: // statements -> if_stmt
#line 98 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
				}
#line default
        break;
      case 19: // statements -> while_stmt
#line 102 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
				}
#line default
        break;
      case 20: // statements -> read_stmt, Semicolon
#line 106 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-2].node;
				}
#line default
        break;
      case 21: // statements -> write_stmt, Semicolon
#line 110 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-2].node;
				}
#line default
        break;
      case 22: // statements -> expr_instruction
#line 114 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
				}
#line default
        break;
      case 23: // statements -> return_stmt, Semicolon
#line 118 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-2].node;
				}
#line default
        break;
      case 24: // statements -> block
#line 122 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
				}
#line default
        break;
      case 25: // if_stmt -> If, OpenPar, expr, ClosePar, statements, Else, statements
#line 128 "kompilator.y"
    {
				Compiler.IfElseOp n = new Compiler.IfElseOp(ValueStack[ValueStack.Depth-5].node, ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 26: // if_stmt -> If, OpenPar, expr, ClosePar, statements
#line 133 "kompilator.y"
    {
				Compiler.IfOp n = new Compiler.IfOp(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 27: // while_stmt -> While, OpenPar, expr, ClosePar, statements
#line 142 "kompilator.y"
    {
				Compiler.WhileOp n = new Compiler.WhileOp(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 28: // read_stmt -> Read, Ident
#line 149 "kompilator.y"
    {
				Compiler.ReadOp n = new Compiler.ReadOp(ValueStack[ValueStack.Depth-1].val, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 29: // write_stmt -> Write, expr
#line 156 "kompilator.y"
    {
				Compiler.WriteExprOp n = new Compiler.WriteExprOp(ValueStack[ValueStack.Depth-1].node, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 30: // write_stmt -> Write, Str
#line 161 "kompilator.y"
    {
				Compiler.WriteStrOp n = new Compiler.WriteStrOp(ValueStack[ValueStack.Depth-1].val, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 31: // return_stmt -> Return
#line 168 "kompilator.y"
    {
				Compiler.ReturnOp n = new Compiler.ReturnOp(Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 32: // expr_instruction -> expr, Semicolon
#line 175 "kompilator.y"
      {
						Compiler.SingleExprInstruction n = new Compiler.SingleExprInstruction(ValueStack[ValueStack.Depth-2].node, Compiler.lineno);
						CurrentSemanticValue.node = n;
						}
#line default
        break;
      case 33: // expr -> Ident, Assign, expr
#line 183 "kompilator.y"
    {
				Compiler.AssignOp n = new Compiler.AssignOp(ValueStack[ValueStack.Depth-1].node, ValueStack[ValueStack.Depth-3].val, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 34: // expr -> exprLogic
#line 188 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
				}
#line default
        break;
      case 35: // exprLogic -> exprLogic, LogicOr, exprRelation
#line 194 "kompilator.y"
    {
				Compiler.BinaryOpLogical n = new Compiler.BinaryOpLogical(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Tokens.LogicOr, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 36: // exprLogic -> exprLogic, LogicAnd, exprRelation
#line 199 "kompilator.y"
    {
				Compiler.BinaryOpLogical n = new Compiler.BinaryOpLogical(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Tokens.LogicAnd, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 37: // exprLogic -> exprRelation
#line 204 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
				}
#line default
        break;
      case 38: // exprRelation -> exprRelation, Equal, exprAdd
#line 210 "kompilator.y"
    {
				Compiler.BinaryOpRelation n = new Compiler.BinaryOpRelation(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Tokens.Equal, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 39: // exprRelation -> exprRelation, NotEqual, exprAdd
#line 215 "kompilator.y"
    {
				Compiler.BinaryOpRelation n = new Compiler.BinaryOpRelation(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Tokens.NotEqual, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 40: // exprRelation -> exprRelation, More, exprAdd
#line 220 "kompilator.y"
    {
				Compiler.BinaryOpRelation n = new Compiler.BinaryOpRelation(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Tokens.More, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 41: // exprRelation -> exprRelation, MoreEqual, exprAdd
#line 225 "kompilator.y"
    {
				Compiler.BinaryOpRelation n = new Compiler.BinaryOpRelation(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Tokens.MoreEqual, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 42: // exprRelation -> exprRelation, Less, exprAdd
#line 230 "kompilator.y"
    {
				Compiler.BinaryOpRelation n = new Compiler.BinaryOpRelation(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Tokens.Less, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 43: // exprRelation -> exprRelation, LessEqual, exprAdd
#line 235 "kompilator.y"
    {
				Compiler.BinaryOpRelation n = new Compiler.BinaryOpRelation(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Tokens.LessEqual, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 44: // exprRelation -> exprAdd
#line 240 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
				}
#line default
        break;
      case 45: // exprAdd -> exprAdd, Plus, exprMul
#line 246 "kompilator.y"
    {
				Compiler.BinaryOpAddMul n = new Compiler.BinaryOpAddMul(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Tokens.Plus, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 46: // exprAdd -> exprAdd, Minus, exprMul
#line 251 "kompilator.y"
    {
				Compiler.BinaryOpAddMul n = new Compiler.BinaryOpAddMul(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Tokens.Minus, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 47: // exprAdd -> exprMul
#line 256 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
				}
#line default
        break;
      case 48: // exprMul -> exprMul, Multiplies, exprBit
#line 262 "kompilator.y"
    {
				Compiler.BinaryOpAddMul n = new Compiler.BinaryOpAddMul(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Tokens.Multiplies, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 49: // exprMul -> exprMul, Divides, exprBit
#line 267 "kompilator.y"
    {
				Compiler.BinaryOpAddMul n = new Compiler.BinaryOpAddMul(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Tokens.Divides, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 50: // exprMul -> exprBit
#line 272 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
				}
#line default
        break;
      case 51: // exprBit -> exprBit, BitOr, exprUn
#line 278 "kompilator.y"
    {
				Compiler.BinaryOpBitwise n = new Compiler.BinaryOpBitwise(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Tokens.BitOr, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 52: // exprBit -> exprBit, BitAnd, exprUn
#line 283 "kompilator.y"
    {
				Compiler.BinaryOpBitwise n = new Compiler.BinaryOpBitwise(ValueStack[ValueStack.Depth-3].node, ValueStack[ValueStack.Depth-1].node, Tokens.BitAnd, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 53: // exprBit -> exprUn
#line 288 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
				}
#line default
        break;
      case 54: // exprUn -> Minus, exprUn
#line 294 "kompilator.y"
    {
				Compiler.UnaryOp n = new Compiler.UnaryOp(ValueStack[ValueStack.Depth-1].node, Tokens.Minus, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 55: // exprUn -> BitNeg, exprUn
#line 299 "kompilator.y"
    {
				Compiler.UnaryOp n = new Compiler.UnaryOp(ValueStack[ValueStack.Depth-1].node, Tokens.BitNeg, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 56: // exprUn -> LogicNeg, exprUn
#line 304 "kompilator.y"
    {
				Compiler.UnaryOp n = new Compiler.UnaryOp(ValueStack[ValueStack.Depth-1].node, Tokens.LogicNeg, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 57: // exprUn -> OpenPar, Int, ClosePar, exprUn
#line 309 "kompilator.y"
    {
				Compiler.UnaryOp n = new Compiler.UnaryOp(ValueStack[ValueStack.Depth-1].node, Tokens.Int, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 58: // exprUn -> OpenPar, Double, ClosePar, exprUn
#line 314 "kompilator.y"
    {
				Compiler.UnaryOp n = new Compiler.UnaryOp(ValueStack[ValueStack.Depth-1].node, Tokens.Double, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 59: // exprUn -> OpenPar, expr, ClosePar
#line 319 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-2].node;
				}
#line default
        break;
      case 60: // exprUn -> value
#line 323 "kompilator.y"
    {
				CurrentSemanticValue.node = ValueStack[ValueStack.Depth-1].node;
				}
#line default
        break;
      case 61: // value -> IntNumber
#line 329 "kompilator.y"
    {
				Compiler.IntNumber n = new Compiler.IntNumber(int.Parse(ValueStack[ValueStack.Depth-1].val));
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 62: // value -> DoubleNumber
#line 334 "kompilator.y"
    {
				double d = double.Parse(ValueStack[ValueStack.Depth-1].val,System.Globalization.CultureInfo.InvariantCulture);
				Compiler.DoubleNumber n = new Compiler.DoubleNumber(d);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 63: // value -> True
#line 340 "kompilator.y"
    {
				Compiler.BoolNumber n = new Compiler.BoolNumber(true);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 64: // value -> False
#line 345 "kompilator.y"
    {
				Compiler.BoolNumber n = new Compiler.BoolNumber(false);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
      case 65: // value -> Ident
#line 350 "kompilator.y"
    {
				Compiler.Ident n = new Compiler.Ident(ValueStack[ValueStack.Depth-1].val, Compiler.lineno);
				CurrentSemanticValue.node = n;
				}
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 357 "kompilator.y"

public Parser(Scanner scanner) : base(scanner) { }
#line default
}
}
